// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMRJRSfLN3hNoVdrLSI2nTiP9aGOaHzYk',
    appId: '1:985972406227:web:bd9fa2c92ce8d454142126',
    messagingSenderId: '985972406227',
    projectId: 'stronglog-105',
    authDomain: 'stronglog-105.firebaseapp.com',
    storageBucket: 'stronglog-105.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcQqn-g6OPUWVqDV223Fak2n5bSRhw0MI',
    appId: '1:985972406227:android:0ff15d3e220e6024142126',
    messagingSenderId: '985972406227',
    projectId: 'stronglog-105',
    storageBucket: 'stronglog-105.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAWBZlmCBOWNOtcuZME50MC6nb6-pC_jU',
    appId: '1:985972406227:ios:d41293e553d90258142126',
    messagingSenderId: '985972406227',
    projectId: 'stronglog-105',
    storageBucket: 'stronglog-105.firebasestorage.app',
    iosBundleId: 'com.example.stronglog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAWBZlmCBOWNOtcuZME50MC6nb6-pC_jU',
    appId: '1:985972406227:ios:d41293e553d90258142126',
    messagingSenderId: '985972406227',
    projectId: 'stronglog-105',
    storageBucket: 'stronglog-105.firebasestorage.app',
    iosBundleId: 'com.example.stronglog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMRJRSfLN3hNoVdrLSI2nTiP9aGOaHzYk',
    appId: '1:985972406227:web:7fd8d62c680f6544142126',
    messagingSenderId: '985972406227',
    projectId: 'stronglog-105',
    authDomain: 'stronglog-105.firebaseapp.com',
    storageBucket: 'stronglog-105.firebasestorage.app',
  );
}
